name: Build Wheels

on:
  push:
    branches:
      - lukev/wheels

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      - run: "export HNSWLIB_NO_NATIVE=true"
        if: matrix.os == 'ubuntu-latest'
      - name: Build
        run: |
          pip install build
          python -m build --wheel
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: python-package-distributions
          path: dist

  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Build sdist
      run: make dist
    - name: Download wheels
      uses: actions/download-artifact@v2
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
